name: APK Generator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setting up Flutter SDK
      uses: subosito/flutter-action@v1
      with:
        channel: stable
    - run: flutter pub get
#     - run: flutter test
    - run: flutter build apk